### ISSUE TITLE
Extension reloading is broken.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Goldy-Bot/Goldy-Bot-Framework#92]
Ordinary extensions seem to be fine but when you reload a package extension (package module) it tends to only reload __init__.py and not the other modules under and sometimes it doesn't reload anything; very confusing behaviour, this is the case with [mal_cord](https://github.com/THEGOLDENPRO/mal_cord).

**Comment by THEGOLDENPRO** [comment]
extension reloading is like completely bricked now, lmao

**Comment by THEGOLDENPRO** [comment]
fixed in `dev12`

**Comment by THEGOLDENPRO** [comment]
broken once again in dev12 but I think this should call for the removal of the command until It's fixed later down the line.

**Comment by THEGOLDENPRO** [comment]
As of ``5.0dev12`` extension reloading will be disabled until further notice or until fixes arrive in later versions. This only affects extensions, reloading for guild and goldy configs will continue to function.

**Comment by Aertic** [comment]
Pro dev timeline: Make -> Breaks -> Fix -> Breaks -> Disable -> Depricate

**Comment by THEGOLDENPRO** [comment]
Closing this as in pancake extension is no longer a thing, the framework is capable of restarting fast and skipping discord command sync if commands are the same.
